// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when watched saved-workflow files change.
 *
 * Treat this as an invalidation signal and re-discover saved workflows when
 * refreshed workflow metadata is needed. Mirrors [`v2::SkillsChangedNotification`].
 */
export type WorkflowsChangedNotification = Record<string, never>;
